; Boolean checks
FALSE EQU 0
TRUE  EQU 1

; flag operations
	const_def
	const FLAG_RESET ; 0
	const FLAG_SET   ; 1
	const FLAG_TEST  ; 2

; DMGPalToGBCPal
CONVERT_BGP  EQU 0
CONVERT_OBP0 EQU 1
CONVERT_OBP1 EQU 2

NUM_COLORS EQU 4
PAL_SIZE EQU NUM_COLORS * 2
NUM_ACTIVE_PALS EQU 4